import { InsertObject, Kysely } from "kysely";
import { DB } from "../../kysely/db";
import {
  ICategoryType,
  IRVendorFetchReqBody,
  IVenderCreateReq,
  IVendorAddProductReq,
  IVendorLogin,
} from "../utils/types";
import { createDate } from "../utils/utils";
import { Log } from "../utils/Log";
import { HttpError } from "../utils/HttpError";
import { HttpStatusCode } from "../utils/HttpStatusCodes";

export class vendorsSqlOps {
  static async getVendors(
    sqlClient: Kysely<DB>,
    requestBody: IRVendorFetchReqBody
  ) {
    const PAGE_SIZE =
      requestBody.pageSize ?? Number(process.env.PAGE_SIZE) ?? 40;
    if (!requestBody.sort) {
      requestBody.sort = {
        path: "created_on",
        direction: "desc",
      };
    }
    if (!requestBody.pageNo) {
      requestBody.pageNo = 1;
    }
    const total_vendors = await sqlClient
      .selectFrom("vendors")
      .$if(!!requestBody.searchStr, (qb) =>
        qb.where((eb) =>
          eb.or([eb("name", "ilike", `%${requestBody.searchStr}%` as string)])
        )
      )
      .select((eb) => eb.fn.countAll<number>().as("total_vendors"))
      .execute();
    const totalCount = total_vendors[0].total_vendors;

    const OFFSET = PAGE_SIZE * (requestBody.pageNo - 1);

    const vendors = await sqlClient
      .selectFrom("vendors")
      .$if(!!requestBody.searchStr, (qb) =>
        qb.where((eb) =>
          eb.or([eb("name", "ilike", `%${requestBody.searchStr}%` as string)])
        )
      )
      .orderBy(requestBody.sort.path, requestBody.sort.direction)
      .limit(PAGE_SIZE)
      .offset(OFFSET)
      .select([
        "id",
        "name",
        "contact_no",
        "email",
        "address",
        "created_on",
        "website",
        "company_name",
      ])
      .execute();

    const hasMore = OFFSET + PAGE_SIZE < totalCount ? true : false;
    return {
      vendors,
      totalCount,
      hasMore,
    };
  }

  static async storeVendors(
    sqlClient: Kysely<DB>,
    userId: string,
    reqBody: IVenderCreateReq
  ) {
    const productCategories = reqBody.productCategories;
    const now = createDate();
    const response = await sqlClient.transaction().execute(async (db) => {
      const [storeVendorRes] = await db
        .insertInto("vendors")
        .values({
          name: reqBody.name,
          email: reqBody.email,
          contact_no: reqBody.contactNo,
          created_on: now,
          modified_on: now,
          created_by: userId,
          modified_by: userId,
          address: reqBody.address as any,
          website: reqBody.website ?? null,
          company_name: reqBody.companyName ?? null,
        })
        .returning("id")
        .execute();
      const vendorId = storeVendorRes.id;
      Log.i(`Vendor added successfully, with id ${vendorId}`);

      return {
        isSuccess: true,
        message: `Vendors added successfully!`,
      };
    });
    return response;
  }

  static async addProductToVendor(
    sqlClient: Kysely<DB>,
    userId: string,
    reqBody: IVendorAddProductReq
  ) {
    const now = createDate();
    const [updateRes] = await sqlClient
      .insertInto("product_vendor_map")
      .values({
        product_id: reqBody.productId,
        vendor_id: reqBody.vendorId,
        created_by: userId,
        created_on: now,
        modified_by: userId,
        modified_on: now,
      })
      .returning("id")
      .execute();
    Log.i(`Updated successfully! id ${updateRes.id}`);
    return {
      isSuccess: true,
      message: `updated successfully!`,
    };
  }

  static async vendorLogin(sqlClient: Kysely<DB>, reqBody: IVendorLogin) {
    const { email, password } = reqBody;

    const vendorData = await sqlClient
      .selectFrom("rfq_vendors as rv")
      .leftJoin("vendors as v", "rv.vendor_id", "v.id")
      .where("v.email", "=", email)
      .select(["v.id", "v.name", "rv.passcode", "rv.rfq_id", "rv.product_id"])
      .execute();

    if (vendorData.length < 1) {
      throw new HttpError(HttpStatusCode.FORBIDDEN, `User is not Exists!`);
    }

    if (vendorData[0].passcode !== password) {
      throw new HttpError(
        HttpStatusCode.FORBIDDEN,
        `User email or password wrong!`
      );
    }

    return {
      isSuccess: true,
      vendorInfo: {
        name: vendorData[0].name,
        vendorId: vendorData[0].id,
        rfqId: vendorData[0].rfq_id,
        productId: vendorData[0].product_id,
      },
    };
  }

  static async storeVendorsBulk(sqlClient: Kysely<DB>) {
    const now = createDate();
    const data = [
      {
        company_name: "CUMMINS",
        name: "PARTHA CHATTERJEE",
        email: "pdmasteelsindia@gmail.com , rishikesh.ganjave@cummins.com",
        contact_no: "91 9007320003",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CUMMINS",
        name: "Pankaj Seth",
        email: "sethinfra20@gmail.com",
        contact_no: "91-7980441480",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CUMMINS",
        name: "Vikram Ogale",
        email: "vikramogale@gmail.com",
        contact_no: "91 99751 87558",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CUMMINS",
        name: "Yamile Carpio",
        email: "ycarpio@gopower.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CUMMINS",
        name: "Silvia Llopis Gregori",
        email: "silvia@yorpower.com",
        contact_no: "44(0)7796-131403",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CUMMINS",
        name: "Yu Placido",
        email: "placido.et@gmail.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Trade Promoters (Pvt) Limited",
        name: "Jayamal Senarathna",
        email: "jayamals@etpl.lk",
        contact_no: 94768216275,
        website: "http://www.tpl.lk",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Trade Promoters (Pvt) Limited",
        name: "Sandeep Thakur",
        email: "sandeep.thakur@jakson.com",
        contact_no: 8377890867,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Trade Promoters (Pvt) Limited",
        name: "Mr. Mitul Chatterjee",
        email: "mitul.chatterjee@jakson.com",
        contact_no: "9836777710 , 8420050346",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Trade Promoters (Pvt) Limited",
        name: "Ravi Peeris",
        email: "ravip@etpl.lk , etpl.lk",
        contact_no: "94 777 531675",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Trade Promoters (Pvt) Limited",
        name: "Vinod R Kuchekar",
        email: "vinod.r.kuchekar@cummins.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Trade Promoters (Pvt) Limited",
        name: "Bowen Gu (Mr.)",
        email: "bowen.gu@cummins.com",
        contact_no: "65 9155 5987",
        website: "bowen.gu@cummins.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Maheshwari Mining Pvt. Ltd.",
        name: "Pranshu Ganeriwala",
        email: "pranshu.ganeriwala@maheshwaree.com",
        contact_no: "91-8972748029",
        website: "www.maheshwaree.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Maheshwari Mining Pvt. Ltd.",
        name: "Rajendra Luktuke",
        email: "rajendra.luktuke@garudapower.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SWANS ENGINEERS INDIA",
        name: "Wilson Paul",
        email: "info@swansengineers.com",
        contact_no: 91995291148,
        website: "www.swansengineers.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "TIL LIMITED,",
        name: "Swapnil K Bhaik",
        email: "Swapnil.Bhaik@tilindia.com",
        contact_no: 9820456459,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Cargotec India Pvt. Ltd.",
        name: "Manoj Kulkarni",
        email: "manoj.kulkarni@kalmarglobal.com",
        contact_no: "91 82 91 841929",
        website: "www.kalmarglobal.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "TRILLIUM",
        name: "Simone Roberto Valentini",
        email: "Simone.Valentini@trilliumflow.com",
        contact_no: "39 340 3873 689",
        website: "trilliumflow.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "TRILLIUM",
        name: "ALFREDO PEPE",
        email: "alfredo.pepe@trilliumflow.com",
        contact_no: "971 52 8976 211",
        website: "trilliumflow.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "EUROPAGES",
        name: "Arlett Fouch\u00e9",
        email: "info@visable.com",
        contact_no: "33 (0)1 41 16 49 14",
        website: "www.europages.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Emerson Process Management (India) Pvt. Ltd.",
        name: "Emerson",
        email: "Preferences@emerson.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Emerson Process Management (India) Pvt. Ltd.",
        name: "Daksh Jain",
        email: "Daksh.Jain@Emerson.com",
        contact_no: "91 98714 44295",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Emerson Process Management Chennai Pvt Ltd",
        name: "Partha Mukherjee",
        email: "Mukherjee@emerson.com",
        contact_no: "91 83369 55900",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "MOORE AUTOMATION LIMITED",
        name: "Miya",
        email: "miya@mvme.cn",
        contact_no: "86-18020776792",
        website: "www.automationdcs.com/",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "MOORE AUTOMATION LIMITED",
        name: "Aditya Kumar",
        email: "adityakumar@emerson.com",
        contact_no: "91-9176648084 | 9990831945",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "ReliServ Solution",
        name: "Dnyaneshwar Kamble",
        email: "sales18@reliserv.in",
        contact_no: 917304510918,
        website: "www.reliservsolution.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Valve Parts USA Ltd",
        name: "Patty Clark",
        email: "valvepartsusa@gmail.com",
        contact_no: "216-408-1254",
        website: "www.ValvePartsUSA.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Valve Parts USA Ltd",
        name: "Subhra Duttagupta",
        email: "Subhra.Duttagupta@emerson.com",
        contact_no: 9831811275,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "FIVES",
        name: "Michel KHADIR",
        email: "michel.khadir@fivesgroup.com",
        contact_no: "33 6 76 28 97 90",
        website: "www.fivesgroup.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Forbes Marshall Pvt. Ltd.",
        name: "Somnath Chakraborty",
        email: "somnathc@forbesmarshall.com",
        contact_no: 8910095157,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Forbes Marshall Pvt Ltd",
        name: "Deepan Dasgupta",
        email: "ddasgupta@forbesmarshall.com",
        contact_no: 9962929006,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Forbes Marshall Pvt Ltd",
        name: "Nitin Ashtekar",
        email: "nashtekar@forbesmarshall.com",
        contact_no: "033 6820 2217",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Forbes Marshall Pvt Ltd",
        name: "Srabani Basu",
        email: "sbasu@forbesmarshall.com",
        contact_no: 9433255799,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Vijay Vikram Singh Ranawat",
        email: "vijayvikramsinghranawat10@gmail.com",
        contact_no: 9829406278,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Dushyant Ranawat",
        email: "dushyant.ranawat9@gmail.com",
        contact_no: 8560077055,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "FLW",
        name: "Jess Salazar",
        email: "jessica.salazar@flw.com",
        contact_no: "(800) 576-6308",
        website: "www.flw.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "FLW",
        name: "Jorge Bautista",
        email: "jorge.bautista@flw.com",
        contact_no: "(800) 576-6308",
        website: "www.flw.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "FLW",
        name: "Bryan Ray",
        email: "bryan.ray@flw.com",
        contact_no: "(800) 576-6309",
        website: "www.flw.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Crane Instrumentation & Sampling",
        name: "Sam Dong",
        email: "cdong@cranecpe.com",
        contact_no: "86 136 0116 5926",
        website: "www.hoke.com, www.goreg.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Crane Instrumentation & Sampling",
        name: "Shatrughan Chand",
        email: "Crane Instrumentation & Sampling",
        contact_no: 917249517212,
        website: "www.hoke.com, www.goreg.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Sahil Kothari",
        email: "sahil@synergyinfraprojects.com",
        contact_no: "91 7600015585",
        website: "https://www.synergyinfraprojects.in/",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "ABB",
        name: "RAJIB CHATTERJEE",
        email: "rajib.chatterjee@in.abb.com",
        contact_no: "91 9007008280",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Vihaan Technologies",
        name: "Varun Kothari",
        email: "vihaantechnologies2017@gmail.com",
        contact_no: "91 9830036331",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Xiamen RuiMingSheng Trading Co., Ltd",
        name: "Mr. Martin Chen",
        email: "sales15@htechplc.com / 1871432251@qq.com",
        contact_no: 8613328787063,
        website: "https://www.rms-dcs.com/",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Burckhardt Compression Singapore Pte Ltd",
        name: "Takashi Furukawa",
        email: "takashi_furukawa@jsw.com.sg",
        contact_no: "65 9069 5100",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Burckhardt Compression Singapore Pte Ltd",
        name: "Jason Ooi",
        email: "Jason@jsw.com.sg",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "The Japan Steel Works, LTD",
        name: "Satoshi Takami",
        email: "satoshi_takami@jsw.co.jp",
        contact_no: "81-80-7851-8976",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SNK AMERICA INC.",
        name: "Atsuko Hashimoto",
        email: "ahashimoto@snkamerica.com",
        contact_no: "312-550-3484",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "BARTEC India Pvt. Ltd.",
        name: "Prasad Kulkarni",
        email: "Prasad.Kulkarni@bartec.com",
        contact_no: "91 9717712026",
        website: "www.bartec.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Jayachandra Bearings (INDIA) Pvt Ltd.",
        name: "Jayakumar Palaniswamy",
        email: "jayakumar@jayachandra.in",
        contact_no: "91 98422 60000",
        website: "www.jayachandra.in",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SENSOREX",
        name: "Henry Nguyen",
        email: "henry.nguyen@sensorex.com",
        contact_no: "1 714 895 4344",
        website: "www.sensorex.fr/meggitt",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SENSOREX",
        name: "Sumit Mohanty",
        email: "sumit.mohanty@valmet.com",
        contact_no: 7008636889,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "LINQUIP",
        name: "Nassy Ford",
        email: "nfo@Linquip.com",
        contact_no: "1 (281)3937519",
        website: "https://www.linquip.com.",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "BHEL",
        name: "Abhishek Gupta",
        email: "abhi.gupta@bhel.in",
        contact_no: "91 11 41793510",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Shijiazhuang Indusatrial Pump Factory Co., Ltd.",
        name: "john.fan",
        email: "john.fan@sgb-slurrypump.com",
        contact_no: 8613831125795,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Sumi-Cyclo Drive India Pvt. Ltd.",
        name: "Bimal Jha",
        email: "bimal.jha@shi-g.com",
        contact_no: "91-930423303",
        website: "www.sumitomodrive.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Sumi-Cyclo Drive India Pvt. Ltd.",
        name: "Sunita Mehra",
        email: "sunita.Mehra@shi-g.com",
        contact_no: "91 7420049109",
        website: "https://emeia.sumitomodrive.com/en-de",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Hydrodyne Teikoku (India) Pvt. Ltd.",
        name: "Akshay Rao",
        email: "akshay@hydrodynepumps.com",
        contact_no: "91-8424052308 ,91-22-50592300-30, ",
        website: "www.hydrodynepumps.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Hydrodyne Teikoku (India) Pvt. Ltd.",
        name: "Farhan Manasiya",
        email: "farhan@hydrodynepumps.com",
        contact_no: "91-8424052308 ,+91-22-50592300-30",
        website: "www.hydrodynepumps.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CVI Services & Supply Pte. Ltd.",
        name: "Rajshekar (Raj)",
        email: "Raj@cvisspl.com",
        contact_no: "65-9782 1432",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "WARTSILA",
        name: "Prasant Nayar",
        email: "prasant.nayar@wartsila.com",
        contact_no: "91 9833521149",
        website: "www.wartsila.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Sahil Wadhera",
        email: "sahil.wadhera@emerson.com",
        contact_no: 9560986648,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Daksh Jain",
        email: "Daksh.Jain@emerson.com",
        contact_no: "91 98714 44295",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "INDUSTRIAL SERVICE SOLUTION",
        name: "Jane Deans",
        email: "Jane.Deans@iss-na.com",
        contact_no: "(440) 313-2690 , (440) 729-0008",
        website: "www.eindustrialsolutions.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Shanghai KASTO Construction Machinery Co., Ltd",
        name: "Ivy Han",
        email: "info_kasto@163.com",
        contact_no: "0086 150 2188 7762",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Al Marwan Heavy Machinery",
        name: "Yomna El Zein",
        email: "Hello@almarwan.com",
        contact_no: "971-565433222",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Construction & Mining Equipment Sales Division",
        name: "Nuwan Fernando",
        email: "nuwan.fernando@dimolanka.com",
        contact_no: "94 76 478 8213",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Forbes Marshall Pvt. Ltd.",
        name: "Somnath Chakraborty",
        email: "somnathc@forbesmarshall.com (copy 1)",
        contact_no: 8910095157,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Borkar Anil",
        email: "Anil.Borkar@ksb.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Aswin JK",
        email: "Aswin.JK@ksb.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "KSB SE & Co. KGaA",
        name: "Annett Engelhardt",
        email: "annett.engelhardt@ksb.com",
        contact_no: "49 345 4826 4628",
        website: "https://ksb.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Susann Hauei\u00df (Ms.",
        email: "s.haueiss@mehner-gmbh.de",
        contact_no: "49 (0) 3761 700948",
        website: "www.mehner-gmbh.de",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "KSB LIMITED (Formerly known as KSB PUMPS LIMITED)",
        name: "Amit Brahma",
        email: "Amit.Brahma2@ksb.com",
        contact_no: 918240105184,
        website: "www.ksbindia.co.in  http://ksb.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "KSB LIMITED (Formerly known as KSB PUMPS LIMITED)",
        name: "Arijit Sarker",
        email: "arijit.sarker@ksb.com",
        contact_no: NaN,
        website: "www.ksbindia.co.in",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Souvik Das",
        email: "Souvik.Das@ksb.com",
        contact_no: 8240064237,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "KSB MIL CONTROLS LTD",
        name: "Rajdeep Deb",
        email: "Rajdeep.Deb@ksb.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "VAISHNO ENGINEERING COMPANY",
        name: "Baleshwar Nath sharma",
        email: "bn41171@gmail.com ,vecsharma07@gmail.com",
        contact_no: "9891683487, 8743822190",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "JMD Overseas C/o Rohit Enterprises (India)",
        name: "Ajay Daga",
        email: "sales@jmdpumps.com",
        contact_no: "0 98300 45041",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Flowjet Valves Pvt Ltd.",
        name: "Hiral Panchal",
        email: "billing@flowjetvalve.com",
        contact_no: "91 81286 98385",
        website: "http://www.flowjetvalve.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SUPERTECH",
        name: "Abhay Pasari",
        email: "apasari@stechengg.com",
        contact_no: "91 98300 28218",
        website: "www.stechengg.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Valve Parts USA Ltd",
        name: "Patty Clark",
        email: "valvepartsusa@gmail.com (copy 1)",
        contact_no: "216-408-1254",
        website: "www.ValvePartsUSA.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Nassy Ford",
        email: "info@linquip.com",
        contact_no: "1 (281)3937519",
        website: "https://www.linquip.com.",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Shijiazhuang Indusatrial Pump Factory Co., Ltd.",
        name: "john.fan",
        email: "john.fan@sgb-slurrypump.com (copy 1)",
        contact_no: 8613831125795,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Tecnica Industriale Srl",
        name: "Rita Lucchesi",
        email: "supply@tecnicaindustriale.com",
        contact_no: "39 0805367090",
        website: "www.tecnicaindustriale.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Avinandan Mukherjee",
        email: "Avinandan.Mukherjee@ksb.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "KSB Limited",
        name: "Karthia Sundaram",
        email: "Karthia.Sundaram@ksb.com",
        contact_no: "91 9831642222",
        website: "www.ksbindia.co.in",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "KSB SVERIGE AB",
        name: "B\u00e4ste Kund,",
        email: "offert.se@ksb.com",
        contact_no: "46 31 720 24 00",
        website: "http://ksb.se,",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Advanced Reliability Services",
        name: "FN Wong",
        email: "service@ars-vibration.com",
        contact_no: "65-90188875",
        website: "www.ars-vibration.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SPIRARE Energy Pvt. Ltd.",
        name: "Kusum",
        email: "spirare.sales@gmail.com",
        contact_no: "9289120110, 0124-4049121",
        website: "www.cranecpe.com | www.spirare.co.in",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Industrial Service Solutions",
        name: "Jane Deans",
        email: "Jane.Deans@iss-na.com (copy 1)",
        contact_no: "(440) 729-0008",
        website: "www.eindustrialsolutions.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "M&M Control Service Inc.",
        name: "Josh Bruett",
        email: "Josh.Bruett@mmcontrol.com",
        contact_no: NaN,
        website: "mmcontrol.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Turbomachinery & Process Solutions",
        name: "Avinash Kumar",
        email: "avinash2.kumar@bakerhughes.com",
        contact_no: "91 9560485556",
        website: "bakerhughes.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "MANJIL ENTERPRISES",
        name: "Subhrajeet Patra",
        email: "enterprise.manjil@gmail.com",
        contact_no: 9437288052,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Energy & Equipment",
        name: "Jatin Jain",
        email: "Jatin.Jain@meggitt.com",
        contact_no: "91 9967716052",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "KHAITAN SALES CO",
        name: "Rajesh Khaitan",
        email: "khaitankol@yahoo.co.in",
        contact_no: "9433006790/9874041800",
        website: "www.khaitansalesindia.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Mitsui & Co. India Pvt Ltd",
        name: "Abdul Thameem",
        email: "A.Thameem@mitsui.com",
        contact_no: "91 95661 43933",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Mouser Electronics India Pvt Ltd",
        name: "Yasmine Bohidar",
        email: "Yasmine.Bohidar@mouser.com",
        contact_no: "(080) 42650000",
        website: "www.mouser.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Mouser Electronics India Pvt Ltd",
        name: "Bhuvaneshwari D",
        email: "Bhuvaneshwari.D@mouser.com",
        contact_no: "(080) 42650000",
        website: "www.mouser.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Pankaj Seth",
        email: "sethinfra20@gmail.com (copy 1)",
        contact_no: "91-7980441480",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Green Power International Pvt. Ltd.",
        name: "Vipin Malhotra",
        email: "vipin.malhotra@greenpowerintl.com",
        contact_no: "91 8800692127",
        website: "http://greenpowerintl.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Enggpro Business Solutions Pvt. Ltd.",
        name: "Akash Dubey",
        email: "support@enggpro.com",
        contact_no: 918077390915,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Neles India Pvt. Ltd.(Part of Valmet)",
        name: "Harihara Mahapatra",
        email: "harihara.mahapatra@valmet.com",
        contact_no: "91 9937428441 / +91 9337105293",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Neles India Pvt. Ltd.(Part of Valmet)",
        name: "Sumit Mohanty",
        email: "sumit.mohanty@valmet.com (copy 1)",
        contact_no: 7008636889,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "NIKKISO COSMODYNE",
        name: "Elizabeth Park",
        email: "epark@NikkisoCEIG.com",
        contact_no: "1 562 795 5990",
        website: "www.NikkisoCEIG.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "NIKKISO Competence Center Europe",
        name: "Anches Widmann",
        email: "anches.widmann@lewa.com",
        contact_no: NaN,
        website: "www.lewa.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SUREN ENTERPRISE Pvt. Ltd",
        name: "Aniket Patil",
        email: "aniket@suren.co.in",
        contact_no: "91-9082224618; +91-9833294912",
        website: "www.suren.co.in",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "TANSA Equipments Pvt. Ltd.",
        name: "Mr.Roshan Hundare",
        email: "sales@tansa.co.in",
        contact_no: "91 9321985096",
        website: "www.tansa.co.in",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Goodyear India Limited",
        name: "Alok Kumar Verma",
        email: "alok_verma@goodyear.com",
        contact_no: NaN,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CBIS INTERNATIONAL GROUP",
        name: "ILKER CANOZER",
        email: "icanozer@cbis-group.net",
        contact_no: NaN,
        website: "www.cbis-group.net",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: NaN,
        name: "Simon Siony",
        email: "simonsio@nassaunationalcable.com",
        contact_no: "(516)-713-7414",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Mouser Electronics India Pvt Ltd",
        name: "Naveen Nelson",
        email: "Naveen.Nelson@mouser.com",
        contact_no: "(080) 42650000",
        website: "www.mouser.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Nassau National Cable",
        name: "Natalia Savchuk",
        email: "nats@nassaunationalcable.com",
        contact_no: "516 703 3460",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Green Power International Pvt. Ltd.",
        name: "Vipin Malhotra",
        email: "vipin.malhotra@greenpowerintl.com (copy 1)",
        contact_no: "91 8800692127",
        website: "http://greenpowerintl.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Gainwell Commosales Private Limited,",
        name: "Sunil Wadekar",
        email: "sunil.wadekar@gainwellindia.com",
        contact_no: "91 120 6659000",
        website: "www.gainwellindia.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "EB MACHINERY LTD-Cummins,",
        name: "Yu Placido",
        email: "placido.et@gmail.com (copy 1)",
        contact_no: "86-18682293935",
        website: "www.cummins-spareparts.com : www.cumminsengine.net",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "TRILLIUM FLOW TECHNOLOGY",
        name: "Simone Valentini",
        email: "Simone.Valentini@trilliumflow.com (copy 1)",
        contact_no: "39 340 3873 689",
        website: "trilliumflow.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Forbes Marshall Pvt. Ltd.",
        name: "Somnath Chakraborty",
        email: "somnathc@forbesmarshall.com (copy 2)",
        contact_no: 8910095157,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "ABB India Limited",
        name: "Raju Das",
        email: "raju.das@in.abb.com ",
        contact_no: "9197484 19392",
        website: "abb.com/in",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Maco Corporation (India) Pvt. Ltd.",
        name: "Sumit Ghosh",
        email: "sumit.g@macocorporation.com",
        contact_no: "918450052353 / +919830156959",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Hydraulic and pneumatic machines engineer - OMIM Ltd.",
        name: "Gavril Petrishky",
        email: "gavril@omim-bg.com",
        contact_no: "359 889 713 212, 359 2 9670206",
        website: "https://industrialmall.eu/",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "ROTORK",
        name: "Ganesan, Anitha",
        email: "anitha.ganesan@rotork.com",
        contact_no: "91 9600066714, 044 39555694",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Schneider Electric",
        name: "Sakthivel Palani",
        email: "sakthivel.palani@non.se.com",
        contact_no: "18001030011/18004194272",
        website: "www.se.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CIRCOR",
        name: "Peter Warkentin",
        email: "Peter.warkentin@circor.com",
        contact_no: "49-170-7616978",
        website: "circor.com , schroedahl.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "Flowprotec Speciality Valves LLP",
        name: "Gauri Gaikwad",
        email: "ggauri@flowprotec.com",
        contact_no: 917774840760,
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "FLOWPROTEC Speciality Valves LLP",
        name: "Binoy K.",
        email: "kbinoy@flowprotec.com",
        contact_no: "91 9822321278 ,91 20 66073701",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CIRCOR",
        name: "Egbert Oldenboom",
        email: "Egbert.Oldenboom@circor.com",
        contact_no: "49-160 97923587",
        website: "circor.com | schroedahl.com",
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CIRCOR",
        name: "Manonnmani",
        email: "Manonnmani.bv@emerson.com",
        contact_no: "91 7824881879, 044 6608 6610 ",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "CIRCOR",
        name: "Aditya Kumar",
        email: "adityakumar@emerson.com (copy 1)",
        contact_no: "91-9176648084 | 9990831945",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
      {
        company_name: "SOM & ITC | Pressure Management",
        name: "Nilay Shah",
        email: "Nilay.Shah@Emerson.com",
        contact_no: "91 44 66086647",
        website: NaN,
        created_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
        modified_by: "2NASmmNxIVdrfPyQodbOyOEWRzQ2",
      },
    ];

    const response = await sqlClient.transaction().execute(async (db) => {
      const [storeVendorRes] = await db
        .insertInto("vendors")
        .values(data)
        .execute();
      Log.i(`Vendors added successfully}`);

      return {
        isSuccess: true,
        message: `Vendors added successfully!`,
      };
    });
    return response;
  }
}
